perfconnect.py: Fix bad table generation
Fix an issue when 'perfconnect.py -t' is used:
          File "/usr/lib/python2.7/dist-packages/texttable.py", line 392, in _check_row_size
            % self._row_size
        texttable.ArraySizeError: array should contain 7 elements

Couse of problem: some metric can be absent for some services.
Example:
        'dispatch_server_request' is present only for MDS.